apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-management
  name: customer-management
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: customer-management
    spec:
      containers:
        - image: staillansag/msr-customer-management-v2:latest
          imagePullPolicy: Always
          name: customer-management-msr
          ports:
            - name: metrics
              containerPort: 5555
          volumeMounts:
            - mountPath: "/tmp/license"
              name: licenses
              readOnly: true
          env:
            - name: SAG_IS_CONFIG_PROPERTIES
              value: /opt/softwareag/IntegrationServer/packages/CustomerManagement/application.properties
            - name: DATASOURCE_CLASS
              value: org.postgresql.ds.PGSimpleDataSource
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: databaseUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: databasePassword
            - name: DB_SERVERNAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseName
          livenessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 12
      volumes:
        - name: licenses
          secret:
            secretName: licenses
      imagePullSecrets:
        - name: acrregcred
