apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: customer-management
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer-management
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75