{
 "title": "MSR and Microgateway",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MCGW Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"customer-management-mcgw\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MSR Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"customer-management-msr\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MSR Total service calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sag_is_number_service_invokes{app=\"customer-management\", kubernetes_pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "MSR Total service errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sag_is_number_service_errors_per_minute{app=\"customer-management\", kubernetes_pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "MSR ListCustomers calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sag_is_service_number_access{service=\"CUSTOMERMANAGEMENT.SERVICES:LISTCUSTOMERS\", kubernetes_pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "MSR ListCustomers average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(sag_is_service_requests_avg_exec_millis{service=\"CustomerManagement.services:listCustomers\", code=\"200\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}