apiVersion: v1
kind: Service
metadata:
  name: customer-management
  labels:
    name: customer-management
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 9093
  selector:
    app: customer-management
